spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:// rm-bp1b808g64ggm02i8no.mysql.rds.aliyuncs.com:3306/chronicle_dawnlight
    username: zheep
    password: 15689092595zZ
  redis:
    host: redis-12485.crce178.ap-east-1-1.ec2.redns.redis-cloud.com
    port: 12485
    password: nvX0KCgMyJ2zjlmTv2LFmeBoDn63eUO0
    username: default
    #设置项目访问根路径
    #邮箱基本配置
  mail:
    host: smtp.qq.com
    username: zheep1209@foxmail.com
    password: ajqslorgfadtbich
    port: 465
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB
mybatis:
  configuration:
    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
# 服务端口
server:
  port: 8080
